environment:
  BENCHMARK_PROJECT: BotBuilder.Instrumentation.Benchmarks
version: 1.0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: "%BENCHMARK_PROJECT%\\bin\\%CONFIGURATION%\\%BENCHMARK_PROJECT%.exe"
- cmd: 7z a benchmarks.zip %APPVEYOR_BUILD_FOLDER%\BenchmarkDotNet.Artifacts\results\*.*
artifacts:
  - path: benchmarks.zip
    name: benchmarks
    type: Zip
  - path: '**\*.nupkg'
    name: nuget
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: IcoWTkF8odKgz81qG1teogym/gmUTfziufnid28QYpo4gDCgHkyEwosiQuhykgv/
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: master